export const APP_SERVICE_EMAIL = process.env.NEXT_PUBLIC_APP_SERVICE_EMAIL;
export const APP_PHONE_NUMBER = process.env.NEXT_PUBLIC_APP_PHONE_NUMBER;
export const APP_WHATSAPP_NUMBER = process.env.APP_WHATSAPP_NUMBER;
export const APP_FACEBOOK_URL = process.env.NEXT_PUBLIC_APP_FACEBOOK_URL;
export const APP_INSTAGRAM_URL = process.env.NEXT_PUBLIC_APP_INSTAGRAM_URL;
